# Generated by Django 3.1.3 on 2020-11-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200, null=True)),
                ('second', models.CharField(max_length=200, null=True)),
                ('third', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Материал', 'Материал'), ('Производитель', 'Производитель'), ('Вид', 'Вид')], max_length=50, null=True)),
                ('decsription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Размер', 'Размер'), ('Производитель', 'Производитель')], max_length=50, null=True)),
                ('decsription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Материал', 'Материал'), ('Производитель', 'Производитель'), ('Высота шахты', 'Высота шахты')], max_length=50, null=True)),
                ('decsription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Крепость', 'Крепость'), ('Вкусопередача', 'Вкусопередача'), ('Производитель', 'Производитель')], max_length=50, null=True)),
                ('decsription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineDelivery.bowl')),
                ('coals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineDelivery.coals')),
                ('hookah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineDelivery.hookah')),
                ('tabacco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineDelivery.tabacco')),
            ],
        ),
    ]
