# Generated by Django 3.1.3 on 2020-11-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowl',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coals',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hookah',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tabacco',
            name='category',
        ),
    ]
