# Generated by Django 3.1.3 on 2020-11-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0003_auto_20201111_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='complect',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
