# Generated by Django 3.1.3 on 2020-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0004_complect_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complect',
            name='price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
