# Generated by Django 3.1.3 on 2020-11-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0005_auto_20201113_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='complect',
            name='sale',
            field=models.BooleanField(null=True),
        ),
    ]
