# Generated by Django 3.1.3 on 2020-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0006_complect_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complect',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
