# Generated by Django 3.1.3 on 2020-11-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0007_auto_20201117_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.IntegerField(default=0)),
                ('date_creted', models.DateTimeField(auto_now_add=True)),
                ('complect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineDelivery.complect')),
            ],
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
    ]
