# Generated by Django 3.1.3 on 2020-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDelivery', '0008_auto_20201117_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
